### PR TITLE
Rename LICENSE so GH autodetects it and add license text to footer

### PR DESCRIPTION
**Pull request by naupaka**

### CODE REVIEW

**Comment by naupaka** [comment]
Cleaned this up so it's just the single commit

**Comment by naupaka** [comment]
Not sure if GH cares about UK vs US spellings
https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

**Comment by naupaka** [comment]
This should now also render add text with a link to the license in the footer.

**Comment by naupaka** [comment]
This might address #2

**Comment by alxsimon** [comment]
Thanks for the additions

**Pull request merged**
